name: Folder cache

on:
  push:
    branches:
      - April15  # Adjust as needed for different branches
  pull_request:
    branches:
      - April15

jobs:
  list-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List contents of the GitHub workspace
      run: ls -la $GITHUB_WORKSPACE
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Create Directory and File
      run: |
        mkdir -p ./cachetestfolder
        echo "pong" > ./cachetestfolder/testfilecache.yaml

    - name: List files in the workspace
      run: ls -la

    - name: Display contents of the file
      run: cat ./cachetestfolder/testfilecache.yaml

    - name: Cache test folder
      id: cache-folderApril15
      uses: actions/cache@v3
      env:
        cache-name: cache-testfolder2
      with:
        #cache files are stored in `./testfolder`
        path: ./cachetestfolder
        key: vidtest2024trythis2April15
        restore-keys: vidtest2024trythis2April15

  cacheoutput:
    needs: list-contents  # Ensures this job runs after the list-contents job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore Cached Folder
      id: cache-restoreApril15
      uses: actions/cache@v3
      with:
        path: ./cachetestfolder
        key: vidtest2024trythis2April15
        restore-keys: vidtest2024trythis2April15

    - name: List restored files
      run: ls -la ./cachetestfolder
      if: steps.cache-restoreApril15.outputs.cache-hit == 'true'

    - name: Check restored contents
      run: cat ./cachetestfolder/testfilecache.yaml
      if: steps.cache-restoreApril15.outputs.cache-hit == 'true'


# name: Caching folder
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Cache node modules
#         id: cache-npm
#         uses: actions/cache@v3
#         env:
#           cache-name: cache-node-modules
#         with:
#           # npm cache files are stored in `~/.npm` on Linux/macOS
#           path: ~/.npm
#           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-build-${{ env.cache-name }}-
#             ${{ runner.os }}-build-
#             ${{ runner.os }}-

#       - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
#         name: List the state of node modules
#         continue-on-error: true
#         run: npm list

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Test
#         run: npm test
# Using contexts to create cach
